//===========================================================================
//
// SevHUD
//
// ZScript code: Copyright (C) 2020 - 2026 Nash Muhandes
// Modifications: Copyright (C) 2026 SeventhSentinel
//
// License: GPLv3
//
//===========================================================================

class SevHUDHandler : EventHandler
{
	override void PlayerEntered(PlayerEvent e)
	{
		SetupHealthBarTracer(e);
	}

	void SetupHealthBarTracer(PlayerEvent e)
	{
		PlayerInfo plr = players[e.PlayerNumber];
		if (plr && plr.mo)
			plr.mo.A_GiveInventory("SevHUDHealthTracer");
	}
}
